### ISSUE TITLE
Suggest transitioning from Oguri (no longer maintained) to swww (actively maintained)

### ISSUE THREAD

**Issue by tfwiii** [hexive/sunpaper#20] opened 2022-08-31 10:41 UTC
https://github.com/Horus645/swww

```
Why

There are two main reasons that compelled me to make this, the first, that [oguri](https://github.com/vilhalmer/oguri) hasn't updated in over a year as I am writting https://github.com/vilhalmer/oguri/issues/38 (02 Feb 2022), despite there being serious problems with excess of memory use while displaying certain gifs (see this,for example). The best alternative I've found for oguri was [mpvpaper](https://github.com/GhostNaN/mpvpaper), but if felt like quite the overkill for my purposes.

Comparing to oguri, swww uses less cpu power to animate once it has cached all the frames in the animation. It should also be significantly more memory efficient.

The second is that, to my knowledge, there is no wallpaper daemon for wayland that allows you to change the wallpaper at runtime. That is, is order to, for example, cycle through the images of a directory, you'd have to kill the daemon and restart it. Not only does it make simple shell scripts a pain to write, it makes switching from one image to the next to happen very abruptly.
```

**Comment by hexive** [comment] 2022-11-18 14:49
Duplicate of #18

**Closed as completed by hexive** 2022-11-18 14:49 UTC
